spring.application.name=easyrag-local
spring.application.name=easy-rag-qwen
# URL padrão do Ollama rodando localmente
spring.ai.ollama.base-url=http://localhost:11434
# Definindo o modelo de chat principal
#spring.ai.ollama.chat.options.model=qwen2.5-coder:7b
spring.ai.ollama.chat.options.model=llama3.1
# Opcional: Define a criatividade da resposta (0.0 mais exato para RAG, 1.0 mais criativo)
spring.ai.ollama.chat.options.temperature=0.4